#version: '3'
#services:
#  web:
#    build: .
#    ports:
#      - "5000:5000"  # Прокинуть порт 5000 из контейнера на хост
##    environment:
##      - DOCKERIZED:True
#    depends_on:
#      - db  # Указать зависимость от сервиса базы данных
#    links:
#      - db
#  db:
#    image: mysql:latest
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: root
version: '3'
services:
  mysql-container:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql-container

